# Generated by Django 5.2.6 on 2025-10-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_businessarea_companysize_demouser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demouser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
